In [1]:
import numpy as np 
import pandas as pd

In [2]:
df= pd.read_csv(r"spam.csv",encoding='ISO-8859-1')

In [4]:
df.shape

(5572, 5)

In [5]:
df=df.iloc[:,0:2]

In [6]:
df

v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [7]:
df.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [8]:
import matplotlib.pyplot as plt

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer

In [10]:
tfidf= TfidfVectorizer(decode_error="ignore")

In [11]:
df.columns=['labels','data']

In [21]:
tfidf

TfidfVectorizer(decode_error='ignore')

In [12]:
x= tfidf.fit_transform(df['data'])

In [13]:
df['b_labels']=df['labels'].map({'ham':0,'spam':1})
y=df['b_labels'].values

In [22]:
y

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
Xtrain, Xtest, Ytrain, Ytest = train_test_split(x, y, test_size=0.33)

In [23]:
Xtrain

<3733x8672 sparse matrix of type '<class 'numpy.float64'>'
	with 49624 stored elements in Compressed Sparse Row format>

In [24]:
Xtest

<1839x8672 sparse matrix of type '<class 'numpy.float64'>'
	with 24292 stored elements in Compressed Sparse Row format>

In [25]:
Ytrain

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [26]:
Ytest

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [16]:
from sklearn.svm import SVC
model= SVC(kernel='linear',C=2)

In [17]:
from datetime import datetime
t0 = datetime.now()

model.fit(Xtrain, Ytrain)

print("train duration:", datetime.now() - t0)
t0 = datetime.now()
print("train score:", model.score(Xtrain, Ytrain), "duration:", datetime.now() - t0)
t0 = datetime.now()
print("test score:", model.score(Xtest, Ytest), "duration:", datetime.now() - t0)

train duration: 0:00:01.280881
train score: 0.999196356817573 duration: 0:00:01.175980
test score: 0.9820554649265906 duration: 0:00:00.604162


In [27]:
model

SVC(C=2, kernel='linear')